---
title: "Physical environmental (i.e. geospatial) DataSchema"
output: html_document
---
# Table of Contents
1. [Natural environment - Urban Atlas subdomain] #(Natural-environment - Urban-Atlas-subdomain)  
2. [Natural environment - CORINE subdomain] #(Natural-environment - CORINE-subdomain)  
3. [Built environment - Urban Atlas subdomain] #(Built-environment - Urban-Atlas-subdomain)  
4. [Built environment - CORINE subdomain] #(Built-environment - CORINE-subdomain)  
5. [Land use - Urban Atlas subdomain] #(Land-use - Urban-Atla-subdomain)  
6. [Land use - CORINE subdomain] #(Land-use - CORINE-subdomain)  
7. [Built environment - Urban Atlas subdomain] #(Built-environment - Urban-Atlas-subdomain)  

# Natural environment - Urban Atlas  

### **Variable label**: Distance to green urban areas  
**Variable name**: physenv_ua_ne_greenurban  
**Variable description**: Absolute distance to the nearest polygon marked as green urban area  
**Variable type**: decimal  
**Variable unit**: meters  
**Category coding**: -  

**Harmonization status**:    
**Harmonization comment**:    
**R script**:  
```{r, echo=TRUE}
#This is where the R-script will be written


